[package]
name = "ace"
version = "0.1.0"
edition = "2021"

[lib]
name = "ace"
crate-type = ["cdylib"]

[dependencies]
arma-rs = { version = "1.10.5", features = ["uuid"] }
uuid = { version = "1.7.0", features = ["v4"] }
rand = "0.8.5"
rand_chacha = "0.3.1"

# Artillery
rayon = "1.8.1"

# Clipboard
clipboard = { version = "0.5.0", optional = true }

[build-dependencies]
git2 = "0.18.1"

[features]
default = ["clipboard"]
